#include "simple_os_defs.h"

#ifdef WIN32
const uint32_t UTIL_CREATE_ALWAYS = CREATE_ALWAYS;//CREATE_ALWAYS;
const uint32_t UTIL_CREATE_NEW = CREATE_NEW;// CREATE_NEW;
const uint32_t UTIL_OPEN_ALWAYS = OPEN_ALWAYS;// OPEN_ALWAYS;
const uint32_t UTIL_OPEN_EXISTING = OPEN_EXISTING;// OPEN_EXISTING;
const uint32_t UTIL_TRUNCATE_EXISTING = TRUNCATE_EXISTING;// TRUNCATE_EXISTING;
#else
const uint32_t UTIL_CREATE_ALWAYS = O_RDWR | O_CREAT | O_TRUNC;
const uint32_t UTIL_CREATE_NEW = O_RDWR | O_CREAT | O_EXCL | O_TRUNC;
const uint32_t UTIL_OPEN_ALWAYS = O_RDWR | O_CREAT;
const uint32_t UTIL_OPEN_EXISTING = O_RDWR;
const uint32_t UTIL_TRUNCATE_EXISTING = O_RDWR | O_TRUNC;
#endif